spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quackr
    username: quackr
    password: quackr
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8084
  servlet:
    context-path: /quackr/rest/v1